# Generated by Django 4.2.7 on 2026-04-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='城市名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='城市代码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='机房名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='机房代码')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='机房地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datacenters', to='hosts.city', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('root_password', models.CharField(max_length=256, verbose_name='Root密码(加密)')),
                ('password_updated_at', models.DateTimeField(auto_now=True, verbose_name='密码更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='hosts.city', verbose_name='所在城市')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='hosts.datacenter', verbose_name='所在机房')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_password', models.CharField(max_length=256, verbose_name='加密后的密码')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前密码')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_histories', to='hosts.host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '密码历史',
                'verbose_name_plural': '密码历史',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='HostStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_count', models.IntegerField(default=0, verbose_name='主机数量')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hosts.city', verbose_name='城市')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hosts.datacenter', verbose_name='机房')),
            ],
            options={
                'verbose_name': '主机统计',
                'verbose_name_plural': '主机统计',
                'ordering': ['-stat_date', 'city', 'datacenter'],
                'unique_together': {('city', 'datacenter', 'stat_date')},
            },
        ),
    ]
